### ISSUE TITLE
Errorr decrypt: thread 'main' panicked at 'range end index 16 out of range for slice of length 0', src\main.rs:206:68 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### ISSUE THREAD

**Issue by kroast2432423** [valaphee/mcrputil#13]
For some reason, this error does not occur on all packs.

Full error:
```
C:\Users\user>mcrputil decrypt "C:\Users\user\Desktop\ecnrypted\tLZvZLcpRwE=" "C:\Users\user\Desktop\decrypted\tLZvZLcpRwE="
Decrypted contents.json with key 7JNkV1d4NK0aWq51U1jkGdgNiYC5fcJq
thread 'main' panicked at 'range end index 16 out of range for slice of length 0', src\main.rs:206:68
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

C:\Users\user>
```

**Key and source pack are in the same directory and everything is fine with them**
![Screenshot_145](https://github.com/valaphee/mcrputil/assets/134645954/5006f588-dc90-40de-9f5e-1406b1880a61)

**Comment by valaphee** [comment]
Heya, what's the content of your key file?

**Comment by kroast2432423** [comment]
![image](https://github.com/valaphee/mcrputil/assets/134645954/ae309574-995f-4d27-81ee-b4eeef03dd04)

**Comment by valaphee** [comment]
The error you posted, means that your key file was empty (length=0)

The file should only contain 32 characters (a-Z,0.9) - no newline or anything else

**Comment by xxAROX** [comment]
Got same error:
```
thread 'main' panicked at 'range end index 16 out of range for slice of length 0', src\main.rs:206:68
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
``` 

`mcrputil.exe decrypt -k BpLnfgDsc2WD8F2qNfHK5a84jjJkwzDk C:\Users\kfeig\Documents\Development\xxAROX\packs\127.0.0.1\encrypted_example\ C:\Users\kfeig\Documents\Development\xxAROX\packs\127.0.0.1\ExamplePack\`


---

- [x] The key is correct
- [x] packs\127.0.0.1\encrypted_example path exists

encrypted files in this pack:
![grafik](https://github.com/valaphee/mcrputil/assets/57589973/e4a6c7ff-ca18-4bdf-9c5a-ca6ee30c7efc)

**Comment by valaphee** [comment]
Ah I looked at wrong revision,

I'll add a skip for files which are not decryptable / have an invalid length key.
