### ISSUE TITLE
Able to use in linux?

### ISSUE THREAD

**Issue by robokedi** [valaphee/mcrputil#15]
Hi. Able to use this tool in linux terminal?

**Comment by valaphee** [comment]
Sure, you can clone this repository and build it yourself simply by using

git clone https://github.com/valaphee/mcrputil.git # Cloning repository
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh # Installing Rustup
cd mcrputil
cargo run # Compiles and runs the program

Or

by using the pre-build one in https://github.com/valaphee/mcrputil/releases/tag/1.1.5 "mcrputil"

**Comment by robokedi** [comment]
Thanks but me how to use this? Like ./mcrputil etc.

**Comment by robokedi** [comment]
@valaphee

**Comment by robokedi** [comment]
Thanks but me how to use this? Like ./mcrputil etc.

**Comment by valaphee** [comment]
Like described in the README for encryption:
./mcrputil encrypt <inputdir> <outputdir>

the key needed will be displayed after "Encryption finished, key: <key to note>"

inputdir is basically just the unzipped resource pack
