### ISSUE TITLE
The system cannot find the file specified 

### ISSUE THREAD

**Issue by RealYXNG** [valaphee/mcrputil#2]
### _**Error Message:**_

 `Error: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }`

Tried to decrypt this with the correct key and everything, I also made sure it's the correct directory but every time I keep getting this error.

It only decrypts 1 file as an Output which is **License.txt**

**Comment by RealYXNG** [comment]
There's also this error:
`Error: Error("expected value", line: 1, column: 1)`

**Comment by stevei5mc** [comment]
How do you use it?

**Comment by valaphee** [comment]
Fixed with version 1.0.1, and please don't include resource packs as they are copyrighted and not for distribution.
