### ISSUE TITLE
Add  default dont Encrypt file

### ISSUE THREAD

**Issue by stevei5mc** [valaphee/mcrputil#3]
Add  default dont Encrypt file
  default dont Encrypt file:
   manifest.json
   pack_icon.png

**Comment by stevei5mc** [comment]
![Screenshot_20221121_201214_com microsoft rdc android](https://user-images.githubusercontent.com/82391055/203055030-6ba46a0a-0474-4cc6-9800-5de77f3e4b18.png)

**Comment by valaphee** [comment]
Fixed with version 1.0.1
