### ISSUE TITLE
Error: Error("Access is denied. (os error 5)", line: 0, column: 0)

### ISSUE THREAD

**Issue by SugarPocket** [valaphee/mcrputil#4]
Error: Error("Access is denied. (os error 5)", line: 0, column: 0)   version 1.1.0 ,   my os windows 11

**Comment by valaphee** [comment]
What is the command you were using?

**Comment by SugarPocket** [comment]
![alt text](https://sv1.picz.in.th/images/2022/12/06/G6cRY0.png)

en encrypt C:\Users\kitti\OneDrive\เอกสาร\ui\ui C:\Users\kitti\OneDrive\เอกสาร\ui\out

**Comment by SugarPocket** [comment]
> What is the command you were using?

![alt text](https://sv1.picz.in.th/images/2022/12/06/G6cRY0.png)

en encrypt C:\Users\kitti\OneDrive\เอกสาร\ui\ui C:\Users\kitti\OneDrive\เอกสาร\ui\out

> What is the command you were using?

![alt text](https://sv1.img.in.th/cdM7t.png)

en encrypt C:\Users\kitti\OneDrive\เอกสาร\ui\ui C:\Users\kitti\OneDrive\เอกสาร\ui\out

![alt text](https://sv1.img.in.th/cd07X.png)

**Comment by valaphee** [comment]
Could you check if this problem still exists with version 1.1.1?

https://github.com/valaphee/mcrputil/releases/tag/1.1.1

**Comment by SugarPocket** [comment]
> Could you check if this problem still exists with version 1.1.1?
> 
> https://github.com/valaphee/mcrputil/releases/tag/1.1.1

![alt text](https://sv1.img.in.th/gwhtp.png)

it work, thank you for support
