### ISSUE TITLE
Error: key must be a string at line 86 column 53

### ISSUE THREAD

**Issue by SirvGamer** [valaphee/mcrputil#5]
Error: key must be a string at line 86 column 53

Command: .\mcrputil encrypt C:\Users\User\Documents\Pack\unencrypted C:\Users\User\Documents\Pack\encrypted

**Comment by SirvGamer** [comment]
Just as an addition: All files were encrypted. But one of them was not. (server_form.json)

Maybe this can help. I myself have no idea about Rust and I don't know anything about Rust.

Have also tried another version. But these do not work for me either. Also the own build did not work.

I hope this information can help!

**Comment by stevei5mc** [comment]
It is recommended to check the server_ form.json Whether there are grammar problems Or check whether the file is set as unencrypted

**Comment by SirvGamer** [comment]
Oh. I forgot to remove the comments (//) in the JSON file. After removing these it worked!
