### ISSUE TITLE
Encryption problems

### ISSUE THREAD

**Issue by stevei5mc** [valaphee/mcrputil#7]
Found a problem
Encrypting problems occur when the resource pack reaches a certain number of files
This problem leads to the application of the encrypted packet to the server, and the content cannot be fully displayed to the player

**Comment by stevei5mc** [comment]
[test pack](https://github.com/MCspruce/Cube-UI)
Encryption:

https://user-images.githubusercontent.com/82391055/208422209-0e66c759-9e20-4a39-a57c-3609e37d1db8.mp4


No encryption:

https://user-images.githubusercontent.com/82391055/208423325-5be8c17f-a4b9-4d1b-8237-412d9c4668b6.mp4

**Comment by valaphee** [comment]
Had to do with comments, is fixed with 1.1.4. Now comments should also be stripped from json files when encrypting.
