### ISSUE TITLE
Encryption issue

### ISSUE THREAD

**Issue by SinonCute** [valaphee/mcrputil#8]
The pack doesn't work after encrypted but Minecraft still can read it.

**Comment by SinonCute** [comment]
and "Error: missing field `version` at line 1 column 60975"

**Comment by valaphee** [comment]
You mean, the encrypted pack works, but you can't decrypt it anymore?

**Comment by SinonCute** [comment]
Yes, minecraft can read well but can't decrypt it.

**Comment by SinonCute** [comment]
Solved on my own
