### ISSUE TITLE
Error encrypting images and json in texture

### ISSUE THREAD

**Issue by iAldrich23xX** [valaphee/mcrputil#9]
(If you put the .key)

**Not encrypted:**

![image](https://user-images.githubusercontent.com/39071289/210859791-3ac8ebcd-b63f-4775-a2d9-f99155d11575.png)

**Encrypted:**

![image](https://user-images.githubusercontent.com/39071289/210860153-ac5920b1-8c61-4efb-9755-a0c12acf23e2.png)

**Comment by valaphee** [comment]
Hey,
can you share the output of your console?

**Comment by iAldrich23xX** [comment]
> 

![image](https://user-images.githubusercontent.com/39071289/211001436-c44297c3-11c6-4da2-a063-d3052ddf5751.png)


There is no error or anything, it is simply not possible to see the texture in game correctly.

**Comment by valaphee** [comment]
Hmm,
could you sent your unencrypted, and encrypted resource pack with key, to iam@valaphee.com, that I could take a look?

**Comment by iAldrich23xX** [comment]
> Hmm, could you sent your unencrypted, and encrypted resource pack with key, to [iam@valaphee.com](mailto:iam@valaphee.com), that I could take a look?

Sent...

**Comment by xGAMEZAx** [comment]
i had that problem with another encryptor, that why i started searching for alternatives and found this repository

**Comment by xGAMEZAx** [comment]
im having the same issue, minecraft cant read the encrypted data

**Comment by valaphee** [comment]
Ah did you zipped the folder?

For example CloverEncrypt is your output, and you have to manually zip the content again, and rename the key to CloverEncrypt.zip,

and some server softwares don't load .key files atm

**Comment by valaphee** [comment]
For ease of you, I could automate this process in the future

**Comment by xGAMEZAx** [comment]
I'm using bedrock vanilla server, where should i put the key file? Inside My pack?

**Comment by valaphee** [comment]
This is not a vanilla feature and therefore won't work with Vanilla, might be possible, but would require the world to be modified

**Comment by xGAMEZAx** [comment]
Humm and with better altay??

**Comment by iAldrich23xX** [comment]
Indeed, both in pocketmine and in nukkit it is used in .zip and the key in .key format, example (texturepack.zip.key)
